#install required R and bioconductor packages
source("http://www.Bioconductor.org/biocLite.R")
biocLite("BiocUpgrade")

biocLite("edgeR")

#use library
library("edgeR")

#navigate to the directory where you put the downloaded protocol files.
setwd("./Files_for_protocol")

#########################################
# Mesenchymal vs Immunoreactive 
#read the counts data generated by RSEM with sample filter to be the same as the affy expression set.
RNAseq <- read.table( "SupplementaryDataTable2.txt", header = TRUE, sep = "\t", quote="\"",  stringsAsFactors = FALSE,row.names=1)

#load class definitions
classDefinitions_RNAseq <-  read.table( "SupplementaryDataTable4.txt", header = TRUE, sep = "\t", quote="\"",  stringsAsFactors = FALSE)

#filter the dataset
cpms = cpm(RNAseq)
keep = rowSums(cpms > 1) >= 42
counts = RNAseq[keep,]

#exclude genes with ? for names or LOC
exclude <- rownames(counts)[union(grep("\\?",rownames(counts)), grep("^LOC", rownames(counts)))]
counts <- counts[which(!rownames(counts) %in% exclude),]

head( counts[,order(classDefinitions_RNAseq$SUBTYPE)], 5)

d <- DGEList(counts=counts,group=classDefinitions_RNAseq$SUBTYPE)

d = calcNormFactors(d)

#check out how the groups are divided
mds_output <- plotMDS(d, labels=classDefinitions_RNAseq$SUBTYPE, col= c("darkgreen","blue")[factor(classDefinitions_RNAseq$SUBTYPE)])

d = estimateCommonDisp(d)

d = estimateTagwiseDisp(d)

plotMeanVar(d,show.tagwise.vars=TRUE,NBline = TRUE)
plotBCV(d)

de = exactTest(d, pair=c("Immunoreactive","Mesenchymal"))

tt = topTags(de,n=nrow(d))

#create rankfile out of edgeR scored results
ranks_RNAseq <- sign(tt$table$logFC) * -log10(tt$table$PValue)
genenames <- unlist(lapply( rownames(tt$table), function(data) {unlist(strsplit(data,"\\|"))[1]}))
geneids <- unlist(lapply( rownames(tt$table), function(data) {unlist(strsplit(data,"\\|"))[2]}))

ranks_RNAseq <- cbind(genenames, ranks_RNAseq)
colnames(ranks_RNAseq) <- c("GeneName","rank")

write.table(ranks_RNAseq,"MesenchymalvsImmunoreactive_RNAseq_ranks.rnk",col.name=TRUE,sep="\t",row.names=FALSE,quote=FALSE)

#output optional expresion file to be used by Enrichment Map
#expression file should contain the edgeR normalized expression values.
normalized_expression_RNAseq <- cpm(d,normalized.lib.size=TRUE)
genenames <- unlist(lapply( rownames(normalized_expression_RNAseq), function(data) {unlist(strsplit(data,"\\|"))[1]}))
geneids <- unlist(lapply( rownames(normalized_expression_RNAseq), function(data) {unlist(strsplit(data,"\\|"))[2]}))
EM_expressionFile_RNAseq <- cbind(genenames[which(genenames != "?")], geneids[which(genenames != "?")],normalized_expression_RNAseq[which(genenames != "?"),])
colnames(EM_expressionFile_RNAseq)[1] <- "Name"
colnames(EM_expressionFile_RNAseq)[2] <- "geneid"
colnames(EM_expressionFile_RNAseq) <- substring(colnames(EM_expressionFile_RNAseq),1,12)
write.table(EM_expressionFile_RNAseq,"MesenchymalvsImmunoreactive_RNAseq_expression.txt",col.name=TRUE,sep="\t",row.names=FALSE,quote=FALSE)

#write out a class file to be used for Enrichment maps
fileConn<-file("MesenchymalvsImmunoreactive_RNAseq_classes.cls")
writeLines(c(paste(length(classDefinitions_RNAseq[,'SUBTYPE']),"2 1"),paste("# ", unique(classDefinitions_RNAseq[,'SUBTYPE'])[1], " ",unique(classDefinitions_RNAseq[,'SUBTYPE'])[2])), fileConn)
write.table(t(classDefinitions_RNAseq[,'SUBTYPE']),"MesenchymalvsImmunoreactive_RNAseq_classes.cls",col.name=FALSE,sep="\t",row.names=FALSE,quote=FALSE,append=TRUE)
close(fileConn)

####################################################
# compare to other scoring methods recommended by edgeR
#
# GLMfit and QLFfit
#
# comparable methods.  Glm and exact test are more similiar with 0.99961 correlation in FDR
# QLF and exact test have 0.98659 correlation.

group <- factor(classDefinitions_RNAseq$SUBTYPE)
 y <- DGEList(counts=counts,group=group)
 y <- calcNormFactors(y)
 design <- model.matrix(~group)
 y <- estimateDisp(y,design)
 fit <- glmQLFit(y,design)
 qlf <- glmQLFTest(fit,coef=2)
fit_glm <- glmFit(y,design)
glm <- glmLRT(fit_glm,coef=2)
tt_glm <- topTags(glm, n=nrow(y))
tt_qlf <- topTags(qlf, n=nrow(y))

merged_exact_qlf <- merge(tt, tt_qlf, by.x=0, by.y=0)
plot(log(merged_exact_qlf$FDR.x), log(merged_exact_qlf$FDR.y))
cor(log(merged_exact_qlf$FDR.x), log(merged_exact_qlf$FDR.y))
merged_exact_glm <- merge(tt, tt_glm, by.x=0, by.y=0)
plot(log(merged_exact_glm$FDR.x), log(merged_exact_glm$FDR.y))
cor(log(merged_exact_glm$FDR.x), log(merged_exact_glm$FDR.y))


####################################################
# Examine the results using a heatmaps to makes sure there is a separation in out samples
library("pheatmap")
library("RColorBrewer")

#try clustering the columns (annotate with the subtype)
annotation_col <- data.frame(SUBTYPE= factor(classDefinitions_RNAseq[,3]))
rownames(annotation_col) <- classDefinitions_RNAseq[,2]
ann_colors = list(
  SUBTYPE = c(Immunoreactive = "#1B9E77", Mesenchymal = "#D95F02")
)

col.pal <- rev(brewer.pal(11,"RdBu"))
matrix_for_heatmap <- as.matrix(EM_expressionFile_RNAseq[rownames(EM_expressionFile_RNAseq) %in% rownames(tt$table)[which(tt$table$FDR<0.05)],3:dim(EM_expressionFile_RNAseq)[2] ])
class(matrix_for_heatmap) <- "numeric"
matrix_for_heatmap[matrix_for_heatmap == 0] <- 0.0000001

pheatmap(log(matrix_for_heatmap), color = col.pal,
         scale = "row",show_rownames = F, show_colnames = F,main = "heatmap top genes(Mesen vs Immuno) ",
         cluster_rows = TRUE, cluster_cols = FALSE,clustering_distance_rows = "correlation",annotation_col=annotation_col, annotation_colors = ann_colors)


#create a heatmap for the top 10 positive (up regulated) and negative(down regulated) logFC
down <- tt$table$FDR < 0.05 & tt$table$logFC <0
up <- tt$table$FDR < 0.05 & tt$table$logFC >0

matrix_for_heatmap <- as.matrix(EM_expressionFile_RNAseq[rownames(EM_expressionFile_RNAseq) %in% rownames(tt$table)[which(down)[1:10]],3:dim(EM_expressionFile_RNAseq)[2] ])
class(matrix_for_heatmap) <- "numeric"
matrix_for_heatmap[matrix_for_heatmap == 0] <- 0.0000001

pheatmap(log(matrix_for_heatmap), color = col.pal,
         scale = "row",show_rownames = T, show_colnames = F,main = "top 'Down' genes - Immunoreactive specific",
         cluster_rows = TRUE, cluster_cols = FALSE,clustering_distance_rows = "correlation",annotation_col=annotation_col, annotation_colors = ann_colors)

matrix_for_heatmap <- as.matrix(EM_expressionFile_RNAseq[rownames(EM_expressionFile_RNAseq) %in% rownames(tt$table)[which(up)[1:10]],3:dim(EM_expressionFile_RNAseq)[2] ])
class(matrix_for_heatmap) <- "numeric"
matrix_for_heatmap[matrix_for_heatmap == 0] <- 0.0000001

pheatmap(log(matrix_for_heatmap), color = col.pal,
         scale = "row",show_rownames = T, show_colnames = F,main = "top 'Up' genes - Mesenchymal specific",
         cluster_rows = TRUE, cluster_cols = FALSE,clustering_distance_rows = "correlation",annotation_col=annotation_col, annotation_colors = ann_colors)



#########################################
# gprofler files - top genes only

#Mesenchymal vs immunoreactive - mesenchymal only
mesenvsimmuno_mesen_ordered_list <- unlist(lapply(rownames(tt$table[which(tt$table$FDR<0.001 & tt$table$logFC > 0),]), function(data) {unlist(strsplit(data,"\\|"))[1]}))
write.table(mesenvsimmuno_mesen_ordered_list,"mesenvsimmuno_mesenonly_RNAseq_gprofiler.txt",col.name=FALSE,sep="\t",row.names=FALSE,quote=FALSE)

#Mesenchymal vs immunoreactive - immuno only
mesenvsimmuno_immuno_ordered_list <- unlist(lapply(rownames(tt$table[which(tt$table$FDR<0.001 & tt$table$logFC < 0),]), function(data) {unlist(strsplit(data,"\\|"))[1]}))
write.table(mesenvsimmuno_immuno_ordered_list,"mesenvsimmuno_immunoonly_RNAseq_gprofiler.txt",col.name=FALSE,sep="\t",row.names=FALSE,quote=FALSE)

#Mesenchymal vs immunoreactive - both
mesenvsimmuno_list <- unlist(lapply(rownames(tt$table[which(tt$table$FDR<0.001),]), function(data) {unlist(strsplit(data,"\\|"))[1]}))
write.table(mesenvsimmuno_list,"mesenvsimmuno_RNAseq_gprofiler.txt",col.name=FALSE,sep="\t",row.names=FALSE,quote=FALSE)


###########################################
# using enrichment tools provided by edgeR - goana or kegga
# Both are thresholded over-representation analyses. 
biocLite(c("GO.db","org.Hs.eg.db"))

#splice out the entrez gene ids.
temp_names <- rownames(de)
rownames(de) <- unlist(lapply(temp_names,function(x){ unlist(strsplit(x,"\\|"))[2]}))

enrichedGO <- goana(de,geneid=rownames(de), FDR=0.05)

#need to format so we can use it in EM
